import pandas as pd

spotify_data = pd.read_csv(r'Project\Data\data.csv')
spotify_data_genres = pd.read_csv(r'Project\Data\data_w_genres.csv')
spotify_years = pd.read_csv(r'Project\Data\data_by_year.csv')
spotify_genres = pd.read_csv(r'Project\Data\data_by_genres.csv')
spotify_artist = pd.read_csv(r'Project\Data\data_by_artist.csv')

print('Spotify Data')
print(' ')
print('Summary : ')
print(spotify_data.info(verbose=False, null_counts=True))
print(' ')
print('Dimensionality : ')
print(spotify_data.shape)
print(' ')
print('Statistics : ')
print(spotify_data.describe())
print(' ')

print('Spotify Data with Genres')
print(' ')
print('Summary : ')
print(spotify_data_genres.info(verbose=False, null_counts=True))
print(' ')
print('Dimensionality : ')
print(spotify_data_genres.shape)
print(' ')
print('Statistics : ')
print(spotify_data_genres.describe())

print(' ')
print('Spotify Years')
print(' ')
print('Summary : ')
print(spotify_years.info(verbose=False, null_counts=True))
print(' ')
print('Dimensionality : ')
print(spotify_years.shape)
print(' ')
print('Statistics : ')
print(spotify_years.describe())

print(' ')
print('Spotify Genres')
print(' ')
print('Summary : ')
print(spotify_genres.info(verbose=False, null_counts=True))
print(' ')
print('Dimensionality : ')
print(spotify_genres.shape)
print(' ')
print('Statistics : ')
print(spotify_genres.describe())

print(' ')
print('Spotify Artist')
print(' ')
print('Summary : ')
print(spotify_artist.info(verbose=False, null_counts=True))
print(' ')
print('Dimensionality : ')
print(spotify_artist.shape)
print(' ')
print('Statistics : ')
print(spotify_artist.describe())